build:
  version: "3.0"

accounts:
  message: "Hello from cards service"
  contactDetails:
    name: "Card general"
    email: "card@laposte.net"
  onCallSupport:
    - "01 02 03 04 05"
    - "06 07 08 09 10"
