build:
  version: "2.0"

accounts:
  message: "Welcome to prod of loans"
  contactDetails:
    name: "prod (loan) person"
    email: "prod@gmail.com"
  onCallSupport:
    - "01 02 03 04 05"
    - "06 07 08 09 10"