spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Hello from accounts service (qa side)"
  contactDetails:
    name: "qa versop,"
    email: "qa@gmail.com"
  onCallSupport:
    - "01 02 03 04 05"
    - "06 07 08 09 10"