spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "You're on production"
  contactDetails:
    name: "prod versop,"
    email: "prod@gmail.com"
  onCallSupport:
    - "01 02 03 04 05"
    - "06 07 08 09 10"